apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
  creationTimestamp: null
  labels:
    run: ingestion-api
  name: ingestion-api
spec:
  selector:
    run: ingestion-api
  ports:
  - protocol: TCP
    name: "http"
    port: 9080
    targetPort: 9080
    nodePort: 30980
  type: NodePort
status:
  loadBalancer: {}
