apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: ingestion-api
  name: ingestion-api
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ingestion-api
    spec:
      containers:
      - image: "registry.<ibm_cloud_region>.bluemix.net/<namespace>/ingestion-api"
        name: ingestion-api
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        env:
        - name: DEFAULT_SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
             name: apikey
             key: DEFAULT_SERVICE_API_KEY
        - name: DEFAULT_SERVICE_INSTANCE_ID
          valueFrom:
            secretKeyRef:
             name: apikey
             key: DEFAULT_SERVICE_INSTANCE_ID
        - name: DEFAULT_CLOUDFUNCTION_API_KEY
          valueFrom:
            secretKeyRef:
             name: apikey
             key: DEFAULT_CLOUDFUNCTION_API_KEY     
        - name: DEFAULT_IAM_ENDPOINT 
          value: <iam endpoint>
        - name: DEFAULT_ENDPOINT_URL 
          value: <endpoint_url>
        - name: DEFAULT_CLOUDFUNCTION_API_HOST
          value: <cloudfunction_api_host>
        - name: DEFAULT_CLOUDFUNCTION_NAMESPACE
          value: <cloudfunction_namespace>
        - name: DEFAULT_OBJECTBUCKET
          value: <object_bucket_name>
        - name: DEFAULT_METADATABUCKET
          value: <metadata_bucket_name>
        - name: DEFAULT_CLOUDFUNCTION_PARSERS
          value: "{ \"hl7\":\"hl7parsercloudfunction\"}"  
        resources: {}
      hostname: ingestion-api
      restartPolicy: Always
status: {}